name: pureaahar
description: VegVerse - A brand of Pure Aahar
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  carousel_slider: ^4.2.1
  dart_mappable: ^4.2.2
  dio: ^5.5.0+1
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  lottie: ^3.1.2
  phone_numbers_parser: ^8.3.0
  pinput: ^5.0.0
  riverpod_annotation: ^2.3.5
  smart_auth: ^2.0.0
  worker_manager: ^7.0.3

dev_dependencies:
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/vectors/
    - assets/animations/
