// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Q8aH_JSHoBL0Sc3TJ-PijUVGOaZb-C0',
    appId: '1:519229435658:web:00f1580d99fafd14ca94f3',
    messagingSenderId: '519229435658',
    projectId: 'pureaahar-dev',
    authDomain: 'pureaahar-dev.firebaseapp.com',
    storageBucket: 'pureaahar-dev.appspot.com',
    measurementId: 'G-1Q4P10KT76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdO2SK_kONMsRon80JQVnD5tcPx--LFk',
    appId: '1:519229435658:android:008b06da203c9d5aca94f3',
    messagingSenderId: '519229435658',
    projectId: 'pureaahar-dev',
    storageBucket: 'pureaahar-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZ3xaXSHR2FKIzRKs6wJN_0icbBcoIxM',
    appId: '1:519229435658:ios:c2fd70989077ce98ca94f3',
    messagingSenderId: '519229435658',
    projectId: 'pureaahar-dev',
    storageBucket: 'pureaahar-dev.appspot.com',
    androidClientId:
        '519229435658-uf273u2j9fg6aebb5t7v6e5mia4cnh7o.apps.googleusercontent.com',
    iosClientId:
        '519229435658-q8ip3sluv5qledls53q6l1nrepbkda6b.apps.googleusercontent.com',
    iosBundleId: 'com.vegverse.app.dev',
  );
}
