name: pureaahar

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
dependencies:
  dart_mappable: ^4.2.2
  dio: ^5.5.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
